### PR TITLE
respond_to?(:) for < 12.6 compat

### PR DESCRIPTION
**Pull request by tinuva**
### Description

Update metadata.rb so that cookbook works on Chef 12.2. Specifically on AWS OpsWorks Windows stacks fail with the following error before the change:

ERROR: Could not read C:/chef/cookbooks/route53 into a Chef object: undefined method `chef_version' for #<Chef::Cookbook::Metadata:0x2a8b7b8>

### CODE REVIEW

File: metadata.rb [hunk 1]
```diff
@@ -10,6 +10,6 @@
   supports os
 end
 
-source_url       'https://github.com/chef-cookbooks/route53'
-issues_url       'https://github.com/chef-cookbooks/route53/issues'
-chef_version '>= 12.1'
+source_url       'https://github.com/chef-cookbooks/route53' if respond_to?(:source_url)
```
Comment (tas50) [inline metadata.rb]: The URL metadata shouldnt need this for 12.x but chef version definitely does

**Comment by tinuva** [comment]
Updated to only add respond_to?(:) to chef_version
